### ISSUE TITLE
Player can go through some walls/corners

### ISSUE THREAD

**Issue by antoinegag** [DeflatedPickle/Stuck-In-Trouble#15]
While playing I've noticed that in some places if you rotate the board quickly enough the block/cube/player will slip inbetween the wall and the "frame" of the board.

Video showing this: https://i.imgur.com/5O5WIeY.gifv

Using version 1.18.1

**Comment by DeflatedPickle** [comment]
This is a known bug, though I failed to record it.
I suspect that the [DontGoThroughThings](http://wiki.unity3d.com/index.php?title=DontGoThroughThings) script could fix this bug.

**Comment by antoinegag** [comment]
No idea if this is still maintained but gonna close this issue to unpollute my feed.

**Comment by DeflatedPickle** [comment]
Understandable, have a nice day.
